### ISSUE TITLE
`relative_mse` can only handle 2 arguments

### ISSUE THREAD

**Issue by Vertexwahn** [Mira-13/figure-gen#5]
I tried to run an example via `python3 full_size_with_crops.py`

I get the following error:

```
Traceback (most recent call last):
  File "/home/vertexwahn/dev/figure-gen/examples/full_size_with_crops.py", line 6, in <module>
    figure = FullSizeWithCrops(
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/util/templates.py", line 148, in __init__
    self._errors = [
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/util/templates.py", line 149, in <listcomp>
    self.compute_error(reference_image, m)
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/util/templates.py", line 238, in compute_error
    return image.relative_mse(method_image, reference_image, 0.01)
TypeError: relative_mse() takes 2 positional arguments but 3 were given
```

It seems that `templates.py` make use of `relative_mse` which can only handle 2 arguments.

```
    def compute_error(self, reference_image, method_image) -> Tuple[str, List[float]]:
        return image.relative_mse(method_image, reference_image, 0.01)
```

Any hints on how to get around this?

**Comment by pgrit** [comment]
Should be fixed with a8e48188cabdd3a3e6abebfacf57a3b1ac158af5

**Comment by Vertexwahn** [comment]
After the fix I get

```
ERROR: pdflatex reported an error. The .pdf file was copied anyway but likely contains errors.
Traceback (most recent call last):
  File "/home/vertexwahn/dev/figure-gen/examples/full_size_with_crops.py", line 21, in <module>
    figuregen.figure(figure, width_cm=17.7, filename="full_size_with_crops.pdf")
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/figuregen.py", line 420, in figure
    backend.generate(grids, width_cm * 10, filename)
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/backend.py", line 89, in generate
    self.write_to_file(result, filename)
  File "/home/vertexwahn/.local/lib/python3.10/site-packages/figuregen/pdflatex.py", line 80, in write_to_file
    shutil.copy(pdf_filename, filename)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpcxe2rfix/figure.pdf'
```

**Comment by Vertexwahn** [comment]
Solved my problem. The issue can be closed. ;)
